#!/bin/bash
echo `ps -eo pid,command | grep tt-ticker` > /tmp/ttpid
kill -9 `awk '{print $1}' /tmp/ttpid`
echo `ps -eo pid,command | grep newsapiticker` > /tmp/ttpid
kill -9 `awk '{print $1}' /tmp/ttpid`




